name: kitabulazkar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.5

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pdfx: ^2.6.0
  rename: ^3.0.2
  rflutter_alert: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/